---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.42.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: mikefarah/yq@v4.34.2
- name: kubernetes/kubectl@v1.27.4
- name: k0sproject/k0sctl@v0.15.2
- name: derailed/k9s@v0.27.4
