- hosts: vpnservers
  become: yes
  tasks:
    - name: UFW - Allow all access to tcp port 22 (SSH)
      community.general.ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: UFW - Allow all access to tcp port 443 (HTTPS)
      community.general.ufw:
        rule: allow
        port: '443'
        proto: tcp
