- hosts: servers
  become: yes
  vars:
    github_username: honahuku
    script_local_path: ./update_ssh_keys.sh
    script_remote_path: /usr/local/bin/update_ssh_keys.sh

  tasks:
    - name: .ssh の作成
      file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: "0700"

    - name: update_ssh_keys script をリモートにコピー
      copy:
        src: "{{ script_local_path }}"
        dest: "{{ script_remote_path }}"
        mode: "0755"

    - name: SSH keys を更新するための cron を設定する
      cron:
        name: "Update SSH keys from GitHub"
        minute: "0"
        job: "{{ script_remote_path }}"
